const initSqlJs = require('sql.js');
const fs = require('fs');

async function importUsers() {
  const SQL = await initSqlJs();
  const buffer = fs.readFileSync('./school_duty.db');
  const db = new SQL.Database(buffer);
  
  const users = [
    ['22170', 'Madeline Tan', 'admin', '5 Adara', 'Cadet Sergeant'],
    ['22084', 'Nathan', 'student', '5 Acrux', 'Cadet'],
    ['23156', 'Low Yee Shyuen', 'student', '4 Atria', 'Cadet lance Corporal'],
    ['22146', 'Muhammad Harith Safwan bin Husri', 'admin', '5 Atria', 'Cadet Corporal'],
    ['22118', 'Clement Chan Jing Wei', 'admin', '5 Atria', 'Cadet Sergeant'],

    ['24008', 'Dania Zara Emelda Binti Mohd Azrin Fairoz', 'student', '5 Avior', 'Member'],
    ['22034', 'Sharifah Kaseh Al-Khayra Bt Syed Mohd Adli', 'student', '5 Avior', 'Member'],
    ['22085', 'Vishmitra Sri A/P Gobinnath', 'student', '5 Avior', 'Member'],
    ['22071', 'Wan Ahmad Amsyar Zafrie Bin Wan Mohd. Zuhdi', 'student', '5 Avior', 'Member'],
    ['25179', 'Nelesh Ragubalan', 'student', '5 Avior', 'Member'],
    ['26002', 'Maahazzshree A/P Sasitharan', 'student', '5 Avior', 'Member'],
    ['22096', 'Aryan Singh Thandal', 'student', '5 Aludra', 'Member'],
    ['23017', 'Darshika A/P Balasundram', 'student', '5 Aludra', 'Member'],
    ['22153', 'Erina Binti Azuan', 'student', '5 Aludra', 'Member'],
    ['22114', 'Kavinayah A/P R Saravanan', 'student', '5 Aludra', 'Member'],
    ['22117', 'Thiveishnath A/L Gobinnath', 'student', '5 Aludra', 'Member'],
    ['22136', 'Chiranjevi A/L Rajasegaran', 'student', '5 Acrux', 'Member'],
    ['22098', 'Mohamed Samir Bin Mohamed Aslam', 'student', '5 Acrux', 'Member'],
    ['22121', 'Muhammad Arsyad Bin Mohd Ali', 'student', '5 Acrux', 'Member'],
    ['22028', 'Nur Aleeya Sofea Binti Azhar', 'student', '5 Acrux', 'Member'],
    ['22030', 'Nur Irdina Dania Binti Zulkifli', 'student', '5 Acrux', 'Member'],
    ['22014', 'Nurul Iman Binti Abdul Hafiz', 'student', '5 Acrux', 'Member'],
    ['22069', 'Sarvina A/P Thayalan', 'student', '5 Acrux', 'Member'],
    ['25002', 'Sharnya A/P Gantasamy', 'student', '5 Acrux', 'Member'],
    ['22016', 'Syarifah Musfira Binti Syed Mubarak', 'student', '5 Acrux', 'Member'],
    ['22095', 'Wan Irfan Bin Wan Osmera', 'student', '5 Acrux', 'Member'],
    ['22072', 'Adam Iskandar Bin Zulkefli', 'student', '5 Atria', 'Member'],
    ['22177', 'Muhammad Haziq Irfan Bin Khairul Hafiz', 'student', '5 Adara', 'Member'],
    ['22127', 'Nazneen Binti Nou Bal', 'student', '5 Adara', 'Member'],
    ['22012', 'Nur Jannah Bt Muhammad Ismail', 'student', '5 Adara', 'Member'],
    ['22091', 'Nur Qaisara Binti Mohd Hilmi', 'student', '5 Adara', 'Member'],
    ['22013', 'Nurul Ain Binti Hurairol', 'student', '5 Adara', 'Member'],
    ['22158', 'Almira Erina Binti Fazil Muhammad', 'student', '5 Altair', 'Member'],
    ['23123', 'Alisha Parthiben', 'student', '4 Avior', 'Member'],
    ['23030', 'Lee Qing Xuan', 'student', '4 Avior', 'Member'],
    ['24200', 'Muhammad Danial Luqman Bin Mohammad', 'student', '4 Avior', 'Member'],
    ['23167', 'Puteri Mursyidah Binti Hassan', 'student', '4 Avior', 'Member'],
    ['23073', 'Siti Nur\'Anis Batrisyia Bt Mihisharudin', 'student', '4 Avior', 'Member'],
    ['23174', 'Sudessh Raj A/L Keshavaraj', 'student', '4 Avior', 'Member'],
    ['23085', 'Ang Yi Kai', 'student', '4 Aludra', 'Member'],
    ['23023', 'Auji Najla Binti Tameem Ansari', 'student', '4 Aludra', 'Member'],
    ['23024', 'Chian Kai Yi', 'student', '4 Aludra', 'Member'],
    ['23026', 'Emily May Binti Rosly', 'student', '4 Aludra', 'Member'],
    ['25180', 'Nur Sabrina Binti Norizam', 'student', '4 Aludra', 'Member'],
    ['23072', 'Sakeena Binti Mustafa', 'student', '4 Aludra', 'Member'],
    ['23144', 'Syahmi Aiman Bin Shuhaimi', 'student', '4 Aludra', 'Member'],
    ['23177', 'Loh Wern Wern', 'student', '4 Acrux', 'Member'],
    ['23162', 'Nor Aliah Bt Mohd Ali', 'student', '4 Acrux', 'Member'],
    ['23070', 'Puteri Nur Aniyah Faqihah Binti Muhammad Nur Al-Amin', 'student', '4 Acrux', 'Member'],
    ['23049', 'Tan Ke Ying', 'student', '4 Acrux', 'Member'],
    ['23151', 'Ariff Ridhwan Bin Abdul Rashid', 'student', '4 Atria', 'Member'],
    ['23134', 'Kam Wern Shen', 'student', '4 Atria', 'Member'],
    ['23169', 'Siah Pei Shan', 'student', '4 Atria', 'Member'],
    ['23056', 'Janani A/P Dev Chander', 'student', '4 Adara', 'Member'],
    ['23093', 'Nur Adira Aleesya Binti Muhammad Shafiq', 'student', '4 Adara', 'Member'],
    ['23034', 'Nur Alisha Zuleika Binti Azali Ismarizal', 'student', '4 Adara', 'Member'],
    ['23037', 'Nur Azeera Balqis Binti Mohd Hazri', 'student', '4 Adara', 'Member'],
    ['23101', 'Amrita A/P Youvarajan', 'student', '4 Altair', 'Member'],
    ['23028', 'Intan Najwa Binti Ahmad Nazri', 'student', '4 Altair', 'Member'],
    ['23089', 'Mohamad Amzar Danish Bin Mohd Nadzi', 'student', '4 Altair', 'Member'],
    ['23176', 'Nur Raisha Melissa Binti Mohd Bukhairi', 'student', '4 Altair', 'Member'],
    ['24017', 'Kyra Teoh Rui Wen', 'student', '3 Avior', 'Member'],
    ['24020', 'Sharniya A/P Shanmugam', 'student', '3 Avior', 'Member'],
    ['24018', 'Tan Yun Zhi', 'student', '3 Avior', 'Member'],
    ['24031', 'Zahrah Inas Binti Hafiz', 'student', '3 Avior', 'Member'],
    ['24163', 'Emil Bin Ezrin', 'student', '3 Aludra', 'Member'],
    ['24046', 'Gayathrie A/P Karthik', 'student', '3 Aludra', 'Member'],
    ['24047', 'Harrinisri Sithambaram', 'student', '3 Aludra', 'Member'],
    ['24033', 'Luke Heah', 'student', '3 Aludra', 'Member'],
    ['24040', 'Mohammad Orrain Fawwaz Bin Ariff Al Sukor', 'student', '3 Aludra', 'Member'],
    ['24162', 'Tan Bing Zhang', 'student', '3 Aludra', 'Member'],
    ['24171', 'Hakkash A/L Devaraj', 'student', '3 Acrux', 'Member'],
    ['24169', 'Jonathan Lee Joon Jin', 'student', '3 Acrux', 'Member'],
    ['24078', 'Rupasri A/P Nadarajan', 'student', '3 Acrux', 'Member'],
    ['24096', 'Daanusyaa A/P Kumara Devan', 'student', '3 Atria', 'Member'],
    ['24097', 'Darshanasri Vishnu', 'student', '3 Atria', 'Member'],
    ['24102', 'Patriena A/E Erathiaraj', 'student', '3 Atria', 'Member'],
    ['24103', 'Sadhna A/P Sri Vijayaraj', 'student', '3 Atria', 'Member'],
    ['24108', 'Aaron Luqman Bin Shahrazie Zainal', 'student', '3 Adara', 'Member'],
    ['24110', 'Arish Rayyan', 'student', '3 Adara', 'Member'],
    ['24126', 'Deliishaa A/P Suresh Kumar', 'student', '3 Adara', 'Member'],
    ['24127', 'Fatima Zahra Huda Binti Zairin', 'student', '3 Adara', 'Member'],
    ['24130', 'Jeanne Lim', 'student', '3 Adara', 'Member'],
    ['24114', 'Koay Zher Ee', 'student', '3 Adara', 'Member'],
    ['24119', 'Nitish Kumar', 'student', '3 Adara', 'Member'],
    ['24120', 'Qayyim Haziq Bin Saiful Anwar', 'student', '3 Adara', 'Member'],
    ['24134', 'Shivani Balakrishnan', 'student', '3 Adara', 'Member'],
    ['24137', 'Varshini A/P Kumaralingam', 'student', '3 Adara', 'Member'],
    ['24124', 'Vissnu A/L Sivaram @ Shivaram', 'student', '3 Adara', 'Member'],
    ['24150', 'Nivaashini A/P Vijiyandran', 'student', '3 Altair', 'Member'],
    ['25015', 'Airis Zalikha Binti Hilmi Zukri', 'student', '2 Avior', 'Member'],
    ['25019', 'Delisya Nur Amalina Binti Norhizlan', 'student', '2 Avior', 'Member'],
    ['25022', 'Meynissa Zophisx A/P Ai Rin', 'student', '2 Avior', 'Member'],
    ['25023', 'Nik Fateema Aalani Binti Nik Fadzly', 'student', '2 Avior', 'Member'],
    ['25027', 'Nur Izz Zara Binti Rohizir', 'student', '2 Avior', 'Member'],
    ['25052', 'Ariana Zahra Binti Shafiz', 'student', '2 Avior', 'Member'],
    ['25035', 'Amirul Mujahid Bin Hairi', 'student', '2 Aludra', 'Member'],
    ['25036', 'Arif Naufal Bin Rimi Razman', 'student', '2 Aludra', 'Member'],
    ['25045', 'Sanshraay', 'student', '2 Aludra', 'Member'],
    ['25050', 'Anjanaa A/P Youvarajan', 'student', '2 Aludra', 'Member'],
    ['25059', 'Nadin Safeerah Binti Sazali M Ali', 'student', '2 Aludra', 'Member'],
    ['25153', 'Mohammad Ariff Arrian Bin Mohd Faisal', 'student', '2 Acrux', 'Member'],
    ['25154', 'Muhammad Hazim Bin Razali', 'student', '2 Acrux', 'Member'],
    ['25158', 'Kiranraj A/L Karthigeiyan', 'student', '2 Acrux', 'Member'],
    ['25078', 'Jaysharant Prahbu', 'student', '2 Atria', 'Member'],
    ['25088', 'Elsa Binti Johan', 'student', '2 Atria', 'Member'],
    ['25110', 'Muhammad Sayf Yasser Bin Anwar', 'student', '2 Adara', 'Member'],
    ['25111', 'Pravin A/L Partiban', 'student', '2 Adara', 'Member'],
    ['25112', 'Ryan Seah Toh Hao', 'student', '2 Adara', 'Member'],
    ['25118', 'Chan Yi Thung', 'student', '2 Adara', 'Member'],
    ['25122', 'Jenna Choong Hwei Yen', 'student', '2 Adara', 'Member'],
    ['25129', 'Sarvina A/P Sasikumar', 'student', '2 Adara', 'Member'],
    ['25151', 'Pritivkumar A/L Kaneskumar', 'student', '2 Adara', 'Member'],
    ['25175', 'Lavendy Ong Su Shiang', 'student', '2 Altair', 'Member'],
    ['26012', 'Adellea Nur Humaira Binti Mohd Badrul Nisham', 'student', '1 Avior', 'Member'],
    ['26010', 'Loh Wern Jing', 'student', '1 Avior', 'Member'],
    ['26004', 'Muhammad Huzaifah Bin Syawalludin', 'student', '1 Avior', 'Member'],
    ['26008', 'Ong Yu Ern', 'student', '1 Avior', 'Member'],
    ['26019', 'Qaesya Az Zehra Binti Mohd Misyael', 'student', '1 Avior', 'Member'],
    ['26021', 'Zara Nadynne Meah Binti Fazrein Meah', 'student', '1 Avior', 'Member'],
    ['26132', 'Taarendran A/L Kalai Selvan', 'student', '1 Avior', 'Member'],
    ['26022', 'Harshneel Singh A/L Savinder Singh', 'student', '1 Aludra', 'Member'],
    ['26023', 'Jackson Lim Khuan Ee', 'student', '1 Aludra', 'Member'],
    ['26036', 'Jessie Thasyaashree A/P Suryakumar', 'student', '1 Aludra', 'Member'],
    ['26028', 'Noor Faris Adam Bin Noor Shukri', 'student', '1 Aludra', 'Member'],
    ['26029', 'Shahzad Fawwaz Bin Nur Muhammad', 'student', '1 Aludra', 'Member'],
    ['26034', 'Vianne Lim Xin Yen', 'student', '1 Aludra', 'Member'],
    ['26140', 'Thaarun A/L Goeilapalan', 'student', '1 Aludra', 'Member'],
    ['26051', 'Affeirul Uwais Alqarny Bin Affeirul Annas Azzandry', 'student', '1 Acrux', 'Member'],
    ['26060', 'Arissa Amanda Binti Mohammad Effandi', 'student', '1 Acrux', 'Member'],
    ['26050', 'Vidhesh Jagdish', 'student', '1 Acrux', 'Member'],
    ['26148', 'Dhiya Nadhirah Binti Zhafri', 'student', '1 Acrux', 'Member'],
    ['26184', 'Shaik Caliph Danish Bin Shaik Mohd Rizal', 'student', '1 Acrux', 'Member'],
    ['26075', 'Abdul Fattah Bin Abdullah', 'student', '1 Atria', 'Member'],
    ['26100', 'Sachhin Logaindren', 'student', '1 Adara', 'Member'],
    ['26111', 'Tanesha A/P Jayaganthan', 'student', '1 Adara', 'Member'],
    ['26154', 'Koay Xin Yu', 'student', '1 Adara', 'Member'],
    ['26174', 'Jaidev Maheswaran', 'student', '1 Adara', 'Member'],
    ['26175', 'Krya Nair A/P Devendiran Nair', 'student', '1 Adara', 'Member'],
    ['26178', 'Muhammad Aeril Bin Azuari', 'student', '1 Adara', 'Member'],
    ['26125', 'Muhammad Rykarl Qusairy Bin Mohd Abdul Rasul', 'student', '1 Altair', 'Member'],
    ['26162', 'Ryan Teoh Zhen Hao', 'student', '1 Altair', 'Member'],
    ['26163', 'Muhammad Khalid Bin Mohamed Noor', 'student', '1 Altair', 'Member'],
    ['26169', 'Zema Naseeba Binti Zema Zamane', 'student', '1 Altair', 'Member'],
    ['26170', 'Qaelish Az Zehra Binti Mohd Misyael', 'student', '1 Altair', 'Member'],
    ['26180', 'Kisanthini Priya A/P Subramaniam', 'student', '1 Altair', 'Member'],
    ['26187', 'Shaarumathi A/P Chandran', 'student', '1 Altair', 'Member'],
    ['26188', 'Izzara Bt Izhar', 'student', '1 Altair', 'Member']
  ];
  
  users.forEach(u => {
    db.run('INSERT OR REPLACE INTO users (nombor_daftar, full_name, role, class, rank) VALUES (?, ?, ?, ?, ?)', u);
  });
  
  const data = db.export();
  fs.writeFileSync('./school_duty.db', Buffer.from(data));
  console.log('✅ Done');
  db.close();
}

importUsers();